language: julia

os:
  - linux

virt: lxd

group: edge

arch:
  - amd64
  - arm64
  - arm64-graviton2

julia:
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - arch: arm64

notifications:
  email: false

# script:
#   - julia --color=yes -e 'using Pkg; Pkg.build()'
#   - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
#   # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   # - julia --check-bounds=yes -e 'using Pkg; Pkg.develop("KernelDensityEstimate"); Pkg.test("KernelDensityEstimate"; coverage=true)'

jobs:
  fast_finish: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("KernelDensityEstimate")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
